In [51]:
import pandas as pd
import numpy as np
import glob

In [52]:
path_train = './data/train'
path_test = './data/test'
path_saved_models = './data/saved_models'
path_saved_predictions = './data/saved_predictions'

In [53]:
file_names = glob.glob(path_saved_predictions + "/*.csv")
combined_df = pd.DataFrame()

for i, file in enumerate(file_names):
    df = pd.read_csv(file)
    if i == 0:
        combined_df['id'] = df['id']
    combined_df = pd.concat([combined_df, df[['target']].rename(columns={"target":f"target_{i}"})], axis=1)

combined_df

,id,target_0,target_1,target_2,target_3,target_4,target_5,target_6,target_7,target_8
0,4490468,0.007382,0.150812,0.222654,0.219449,0.211415,0.211996,0.210344,0.014782,0.012341
1,4490469,0.004878,0.106707,0.134163,0.124186,0.125330,0.122118,0.089683,0.007196,0.006869
2,4490470,0.015224,0.109717,0.140002,0.132437,0.138580,0.158626,0.200181,0.013757,0.011937
3,4490471,0.069029,0.545191,0.628499,0.514203,0.552192,0.524092,0.573987,0.079836,0.071063
4,4490472,0.125721,0.560482,0.968402,0.968958,0.938448,0.970439,0.973390,0.507758,0.584508
...,...,...,...,...,...,...,...,...,...,...
509527,4949040,0.017433,0.261386,0.142243,0.142697,0.128035,0.113616,0.141126,0.012875,0.008709
509528,4949041,0.504740,0.944286,0.915772,0.907620,0.919166,0.917294,0.908862,0.434472,0.331162
509529,4949042,0.004921,0.102807,0.046148,0.057321,0.088039,0.051862,0.037744,0.004818,0.004629
509530,4949043,0.032258,0.369143,0.259941,0.302204,0.299145,0.299244,0.243292,0.027224,0.033001
509531,4949044,0.009469,0.197997,0.122436,0.156939,0.163153,0.171042,0.102311,0.006985,0.006332

In [54]:
combined_df["target"] = combined_df.drop(columns=['id']).mean(axis=1)
combined_df

,id,target_0,target_1,target_2,target_3,target_4,target_5,target_6,target_7,target_8,target
0,4490468,0.007382,0.150812,0.222654,0.219449,0.211415,0.211996,0.210344,0.014782,0.012341,0.140131
1,4490469,0.004878,0.106707,0.134163,0.124186,0.125330,0.122118,0.089683,0.007196,0.006869,0.080126
2,4490470,0.015224,0.109717,0.140002,0.132437,0.138580,0.158626,0.200181,0.013757,0.011937,0.102273
3,4490471,0.069029,0.545191,0.628499,0.514203,0.552192,0.524092,0.573987,0.079836,0.071063,0.395343
4,4490472,0.125721,0.560482,0.968402,0.968958,0.938448,0.970439,0.973390,0.507758,0.584508,0.733123
...,...,...,...,...,...,...,...,...,...,...,...
509527,4949040,0.017433,0.261386,0.142243,0.142697,0.128035,0.113616,0.141126,0.012875,0.008709,0.107569
509528,4949041,0.504740,0.944286,0.915772,0.907620,0.919166,0.917294,0.908862,0.434472,0.331162,0.753708
509529,4949042,0.004921,0.102807,0.046148,0.057321,0.088039,0.051862,0.037744,0.004818,0.004629,0.044254
509530,4949043,0.032258,0.369143,0.259941,0.302204,0.299145,0.299244,0.243292,0.027224,0.033001,0.207272
509531,4949044,0.009469,0.197997,0.122436,0.156939,0.163153,0.171042,0.102311,0.006985,0.006332,0.104074

In [55]:
combined_df[['id', 'target']].to_csv("i_love_democracy.csv", index=False)